title: My first github pages
author: Naoya Furudono
email: naoyafurudono@prg.tittech.ac.jp
description: > # this means to ignore newlines until "baseurl:"
  My first github pages. This page is only for practice so you may not get interesting content in this page.
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
